import { makeCSSVar } from "@terrazzo/token-tools/css";

/**
 * Terrazzo's CSS plugin lowercases camelCase ids and re-emits aliases
 * without the leading "--". Rewrite the file into the Fusor contract:
 * :root keeps every token, and later themes only redeclare values that differ.
 */
export function finalizeTokensCss(raw, { prefix, themes, themeAttribute, tokenIds }) {
  const rename = new Map();
  for (const id of tokenIds) {
    const rawName = `${prefix}-${id.replaceAll(".", "-")}`;
    const desired = `--${rawName}`;
    rename.set(desired, desired);
    rename.set(rawName, desired);
    rename.set(makeCSSVar(rawName), desired);
    rename.set(makeCSSVar(desired), desired);
  }

  const blocks = topLevelRules(stripComments(raw));
  const bySelector = new Map();
  for (const block of blocks) {
    if (block.selector.trim().startsWith("@")) continue;
    const decls = new Map();
    for (const decl of parseDeclarations(block.body)) {
      const name = rename.get(decl.property) ?? rename.get(decl.property.replace(/^--/, ""));
      if (!name) continue;
      if (!decls.has(name)) decls.set(name, decl.value.trim());
    }
    bySelector.set(normalizeSelector(block.selector), decls);
  }

  const themeSelectors = themes.map((theme, index) => ({
    theme,
    selector: selectorFor(theme, index, themeAttribute),
  }));

  const base = bySelector.get(normalizeSelector(themeSelectors[0].selector));
  if (!base || base.size === 0) {
    throw new Error(
      `Terrazzo output is missing ${themeSelectors[0].selector} declarations.`,
    );
  }

  const sections = [];
  for (const [index, theme] of themeSelectors.entries()) {
    const found = bySelector.get(normalizeSelector(theme.selector));
    if (!found || found.size === 0) {
      throw new Error(`Terrazzo output is missing ${theme.selector} declarations.`);
    }
    const source = index === 0 ? found : diffTheme(base, found);
    sections.push({ theme: theme.theme, selector: theme.selector, decls: source });
  }

  const lines = ["/* Generated by fusor-tokens. Do not edit. */", ""];
  for (const section of sections) {
    lines.push(`${section.selector} {`);
    for (const [name, value] of sortDecls(section.decls)) {
      lines.push(`  ${name}: ${value};`);
    }
    lines.push("}", "");
  }

  const dark = sections.find((section) => section.theme === "dark");
  if (dark) {
    const explicit = themes[0];
    lines.push("@media (prefers-color-scheme: dark) {");
    lines.push(`  :root:not([${themeAttribute}="${explicit}"]) {`);
    for (const [name, value] of sortDecls(dark.decls)) {
      lines.push(`    ${name}: ${value};`);
    }
    lines.push("  }");
    lines.push("}", "");
  }
  const css = `${lines.join("\n").trimEnd()}\n`;
  if (!css.includes("--")) {
    throw new Error("Generated CSS has no custom properties.");
  }
  return css;
}

export function selectorFor(theme, index, themeAttribute) {
  const attr = `[${themeAttribute}="${theme}"]`;
  if (index === 0) return `:root, ${attr}`;
  if (theme === "dark") return `${attr}, .dark`;
  return attr;
}

function diffTheme(base, theme) {
  const next = new Map();
  for (const [name, value] of theme) {
    if (base.get(name) !== value) next.set(name, value);
  }
  if (next.size === 0) {
    throw new Error("Dark theme did not change any token. Check tokens/themes/dark.tokens.json.");
  }
  return next;
}

function sortDecls(decls) {
  return [...decls.entries()].sort((a, b) =>
    a[0].localeCompare(b[0], "en", { numeric: true }),
  );
}

function normalizeSelector(selector) {
  return selector.replace(/\s+/g, " ").trim();
}

function stripComments(css) {
  return css.replace(/\/\*[\s\S]*?\*\//g, "");
}

function topLevelRules(css) {
  const rules = [];
  let i = 0;
  while (i < css.length) {
    while (i < css.length && /\s/.test(css[i])) i++;
    if (i >= css.length) break;
    const start = i;
    let depth = 0;
    let opened = false;
    for (; i < css.length; i++) {
      if (css[i] === "{") {
        depth++;
        opened = true;
      } else if (css[i] === "}") {
        depth--;
        if (opened && depth === 0) {
          i++;
          break;
        }
      }
    }
    const chunk = css.slice(start, i);
    const brace = chunk.indexOf("{");
    if (brace === -1) continue;
    rules.push({
      selector: chunk.slice(0, brace).trim(),
      body: chunk.slice(brace + 1, chunk.lastIndexOf("}")),
    });
  }
  return rules;
}

function parseDeclarations(body) {
  const decls = [];
  for (const rawLine of body.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("@") || line.includes("{")) continue;
    const match = /^(-{0,2}[A-Za-z_][\w-]*)\s*:\s*(.+);$/.exec(line);
    if (match) decls.push({ property: match[1], value: match[2] });
  }
  return decls;
}
