import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CSS_TRANSFORM_SOURCE } from "./css-transform.js";
import { finalizeTokensCss } from "./css.js";
import { partitionTokenFiles } from "./dtcg.js";

const require = createRequire(import.meta.url);
const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export function pipelineDir(cwd) {
  return path.join(cwd, ".fusor-tokens");
}

export function writePipeline(cwd, config, tokenFiles) {
  const dir = pipelineDir(cwd);
  fs.mkdirSync(dir, { recursive: true });
  const resolverFile = path.join(dir, "resolver.json");
  fs.writeFileSync(resolverFile, renderResolver(dir, config, tokenFiles));
  const configFile = path.join(dir, "terrazzo.config.ts");
  fs.writeFileSync(
    configFile,
    renderTerrazzoConfig(config, ".fusor-tokens/resolver.json", config.outFile),
  );
  return { resolverFile, configFile };
}

function relativeRef(fromDir, file) {
  let rel = path.relative(fromDir, file).split(path.sep).join("/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

export function renderTerrazzoConfig(config, resolverPath, outFile) {
  const outDir = path.dirname(outFile).split(path.sep).join("/");
  const filename = path.basename(outFile);
  const blocks = config.themes.map((theme, index) => {
    const selector = index === 0
      ? `:root, [${config.themeAttribute}="${theme}"]`
      : theme === "dark"
        ? `[${config.themeAttribute}="${theme}"], .dark`
        : `[${config.themeAttribute}="${theme}"]`;
    return `        {
          input: { theme: "${theme}" },
          prepare: (contents) => \`${selector} {\\n\${contents}\\n}\`,
        }`;
  });

  return `// Generated by fusor-tokens. Re-run \`fusor-tokens build\` to refresh.
import { defineConfig } from "@terrazzo/cli";
import css from "@terrazzo/plugin-css";

${CSS_TRANSFORM_SOURCE}

export default defineConfig({
  tokens: [${JSON.stringify(resolverPath)}],
  outDir: ${JSON.stringify(outDir === "." ? "." : outDir)},
  plugins: [
    css({
      filename: ${JSON.stringify(filename)},
      variableName: (token) => ${JSON.stringify(`${config.prefix}-`)} + token.id.replace(/\\./g, "-"),
      transform: fusorCssValue,
      permutations: [
${blocks.join(",\n")}
      ],
    }),
  ],
});
`;
}

export function runTerrazzo(cwd, configFile) {
  const cliPkg = require.resolve("@terrazzo/cli/package.json");
  const bin = path.join(path.dirname(cliPkg), "bin", "cli.js");
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [bin, "build", "--config", configFile, "--silent", "--no-lint"], {
      cwd,
      env: process.env,
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve({ stdout, stderr });
      else {
        const detail = (stderr || stdout || "Terrazzo build failed").trim();
        reject(new Error(detail));
      }
    });
  });
}

export async function compileCss(cwd, config, tokenFiles, tokenIds, outFile) {
  writePipeline(cwd, config, tokenFiles);
  const configFile = path.join(pipelineDir(cwd), "terrazzo.config.ts");
  await runTerrazzo(cwd, configFile);
  const rawPath = path.resolve(cwd, outFile);
  if (!fs.existsSync(rawPath)) {
    throw new Error(`Terrazzo did not write ${outFile}.`);
  }
  const css = finalizeTokensCss(fs.readFileSync(rawPath, "utf8"), {
    prefix: config.prefix,
    themes: config.themes,
    themeAttribute: config.themeAttribute,
    tokenIds,
  });
  fs.mkdirSync(path.dirname(rawPath), { recursive: true });
  fs.writeFileSync(rawPath, css);
  return css;
}

export async function compileCssToTemp(cwd, config, tokenFiles, tokenIds) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "fusor-tokens-"));
  try {
    const resolverFile = path.join(tmp, "resolver.json");
    fs.writeFileSync(resolverFile, renderResolver(tmp, config, tokenFiles));
    const outFile = path.join(tmp, "tokens.css");
    const configFile = path.join(tmp, "terrazzo.config.ts");
    const resolverFromCwd = path.relative(cwd, resolverFile).split(path.sep).join("/");
    fs.writeFileSync(configFile, renderTerrazzoConfig(config, resolverFromCwd, outFile));
    await runTerrazzo(cwd, configFile);
    const raw = fs.readFileSync(outFile, "utf8");
    return finalizeTokensCss(raw, {
      prefix: config.prefix,
      themes: config.themes,
      themeAttribute: config.themeAttribute,
      tokenIds,
    });
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

function renderResolver(resolverDir, config, tokenFiles) {
  const { foundation, themes } = partitionTokenFiles(tokenFiles);
  const ref = (file) => ({ $ref: relativeRef(resolverDir, file) });
  return `${JSON.stringify(
    {
      $schema: "https://www.designtokens.org/schemas/2025.10/resolver.json",
      name: "Fusor Tokens",
      version: "2025.10",
      resolutionOrder: [{ $ref: "#/sets/foundation" }, { $ref: "#/modifiers/theme" }],
      sets: { foundation: { sources: foundation.map(ref) } },
      modifiers: {
        theme: {
          default: config.themes[0],
          contexts: Object.fromEntries(
            config.themes.map((theme) => {
              const file = themes.get(theme);
              return [theme, file ? [ref(file)] : []];
            }),
          ),
        },
      },
    },
    null,
    2,
  )}\n`;
}

export function starterRoot() {
  return path.join(packageRoot, "src", "starter");
}
